# Generated by Django 4.2.6 on 2023-10-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='description',
            new_name='bugDescription',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='title',
            new_name='bugTitle',
        ),
    ]
