# Generated by Django 4.2.6 on 2023-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_rename_description_bug_bugdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
