# Generated by Django 4.2.6 on 2023-10-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_bug_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bugTitle',
            field=models.TextField(max_length=200),
        ),
    ]
